# Generated by Django 5.0 on 2025-04-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
