# Generated by Django 5.0 on 2025-04-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
